In [1]:
# ============================================================
# Weather Trend Forecasting: 01 Data Overview (Fixed)
# ============================================================

# Step 0: Fix module import path for 'src' folder
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)
print("Project root added to sys.path:", project_root)

# Step 1: Imports
import pandas as pd
from IPython.display import display

# Step 2: Load Dataset
csv_path = "C:\\Users\\kumar\\OneDrive\\Desktop\\Pm accelerator\\weather-trend-forecast\\data\\raw\\GlobalWeatherRepository.csv"

if not os.path.exists(csv_path):
    raise FileNotFoundError(f"Dataset not found at {csv_path}.")

df = pd.read_csv(csv_path)

# Step 2a: Convert 'last_updated' to datetime
df["last_updated"] = pd.to_datetime(df["last_updated"], errors="coerce")

# Warn if any invalid dates
num_missing_dates = df["last_updated"].isna().sum()
if num_missing_dates > 0:
    print(f"Warning: {num_missing_dates} rows have invalid 'last_updated' dates.")

# Step 2b: Ensure essential columns exist
required_columns = ["location_name", "country"]
for col in required_columns:
    if col not in df.columns:
        print(f"Warning: '{col}' column missing. Filling with 'Unknown'.")
        df[col] = "Unknown"

# Step 3: Display overview
print("Dataset loaded successfully!")
print(f"Shape: {df.shape}\n")
display(df.head())

# Step 4: Dataset Info
print("\n--- Dataset Info ---")
df.info()

print("\n--- Dataset Description ---")
display(df.describe())

# Step 5: Dataset Coverage
print("\n--- Dataset Coverage ---")
print(f"Start date: {df['last_updated'].min()}")
print(f"End date: {df['last_updated'].max()}")
print(f"Number of locations: {df['location_name'].nunique()}")
print(f"Number of countries: {df['country'].nunique()}")

Project root added to sys.path: c:\Users\kumar\OneDrive\Desktop\Pm accelerator\weather-trend-forecast
Dataset loaded successfully!
Shape: (97629, 41)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97629 entries, 0 to 97628
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       97629 non-null  object
 1   location_name                 97629 non-null  object
 2   latitude                      97629 non-null  float64
 3   longitude                     97629 non-null  float64
 4   timezone                      97629 non-null  object
 5   last_updated_epoch            97629 non-null  int64
 6   last_updated                  97629 non-null  datetime64[ns]
 7   temperature_celsius           97629 non-null  float64
 8   temperature_fahrenheit        97629 non-null  float64
 9   condition_text                97629 non-null  object
 10  wind_mph                      97629 non-null  float64
 11  wind_kph                      97629 non-null  float64
 12  wind_degree                   97629 non-null  int64
 13  wind_direction                97629 non-null  object
 14  pressure_mb                   97629 non-null  float64
 15  pressure_in                   97629 non-null  float64
 16  precip_mm                     97629 non-null  float64
 17  precip_in                     97629 non-null  float64
 18  humidity                      97629 non-null  int64
 19  cloud                         97629 non-null  int64
 20  feels_like_celsius            97629 non-null  float64
 21  feels_like_fahrenheit         97629 non-null  float64
 22  visibility_km                 97629 non-null  float64
 23  visibility_miles              97629 non-null  float64
 24  uv_index                      97629 non-null  float64
 25  gust_mph                      97629 non-null  float64
 26  gust_kph                      97629 non-null  float64
 27  air_quality_Carbon_Monoxide   97629 non-null  float64
 28  air_quality_Ozone             97629 non-null  float64
 29  air_quality_Nitrogen_dioxide  97629 non-null  float64
 30  air_quality_Sulphur_dioxide   97629 non-null  float64
 31  air_quality_PM2.5             97629 non-null  float64
 32  air_quality_PM10              97629 non-null  float64
 33  air_quality_us-epa-index      97629 non-null  int64
 34  air_quality_gb-defra-index    97629 non-null  int64
 35  sunrise                       97629 non-null  object
 36  sunset                        97629 non-null  object
 37  moonrise                      97629 non-null  object
 38  moonset                       97629 non-null  object
 39  moon_phase                    97629 non-null  object
 40  moon_illumination             97629 non-null  int64
dtypes: datetime64[ns](1), float64(23), int64(7), object(10)
memory usage: 30.5+ MB

--- Dataset Description ---

,latitude,longitude,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,97629.000000,97629.000000,9.762900e+04,97629,97629.000000,97629.00000,97629.000000,97629.000000,97629.000000,97629.000000,...,97629.000000,97629.00000,97629.000000,97629.000000,97629.000000,97629.000000,97629.000000,97629.000000,97629.000000,97629.000000
mean,19.146655,22.111870,1.737585e+09,2025-01-23 00:38:03.965829888,22.786695,73.01778,8.239894,13.264101,170.879646,1013.971187,...,18.551144,517.11278,62.741021,15.813762,11.259342,26.146261,53.710302,1.760266,2.760399,49.698512
min,-41.300000,-175.200000,1.715849e+09,2024-05-16 01:45:00,-24.900000,-12.80000,2.200000,3.600000,1.000000,947.000000,...,3.600000,-9999.00000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.726743e+09,2024-09-19 16:30:00,18.100000,64.60000,4.000000,6.500000,83.000000,1010.000000,...,10.500000,237.00000,42.000000,1.295000,0.800000,7.400000,10.900000,1.000000,1.000000,15.000000
50%,17.250000,23.316700,1.737628e+09,2025-01-23 11:30:00,25.000000,77.00000,6.900000,11.200000,165.000000,1013.000000,...,15.900000,327.45000,60.000000,4.995000,2.405000,15.170000,22.100000,1.000000,2.000000,49.000000
75%,40.400000,50.580000,1.748422e+09,2025-05-28 13:15:00,28.300000,82.90000,11.400000,18.400000,256.000000,1018.000000,...,24.400000,507.40000,79.000000,17.945000,9.065000,29.970000,46.065000,2.000000,3.000000,84.000000
max,64.150000,179.220000,1.759219e+09,2025-09-30 21:00:00,49.200000,120.60000,1841.200000,2963.200000,360.000000,3006.000000,...,2970.400000,38879.39800,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000
std,24.457074,65.819474,1.254703e+07,NaN,8.891782,16.00502,7.876606,12.673783,102.722987,11.374869,...,14.675374,843.98154,32.248805,26.059420,40.768717,40.799360,164.028211,0.981358,2.566658,35.055113

--- Dataset Coverage ---
Start date: 2024-05-16 01:45:00
End date: 2025-09-30 21:00:00
Number of locations: 254
Number of countries: 211